version: '3'
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    command:
      - "--pilot.token=${PILOT_TOKEN}"
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./custom/:/custom/
      - ${DATA_FOLDER}/:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`${SUBDOMAIN_TRAEFIK}.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=http,https
      - traefik.http.routers.traefik.tls.certresolver=letsEncrypt
      - traefik.http.middlewares.traefik.headers.SSLRedirect=true
      - traefik.http.middlewares.traefik.headers.STSSeconds=315360000
      - traefik.http.middlewares.traefik.headers.browserXSSFilter=true
      - traefik.http.middlewares.traefik.headers.contentTypeNosniff=true
      - traefik.http.middlewares.traefik.headers.forceSTSHeader=true
      - traefik.http.middlewares.traefik.headers.SSLHost=${DOMAIN}
      - traefik.http.middlewares.traefik.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.traefik.headers.STSPreload=true
      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH}    
networks:
  traefik:
    external: true     