version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab
    hostname: ${SUBDOMAIN_GITLAB}.${DOMAIN}
    networks:
      - traefik
    healthcheck:
      disable: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${SUBDOMAIN_GITLAB}.${DOMAIN}'
        nginx['redirect_http_to_https'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - '${DATA_FOLDER}/.gitlab/config:/etc/gitlab'
      - '${DATA_FOLDER}/.gitlab/logs:/var/log/gitlab'
      - '${DATA_FOLDER}/.gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.rule=Host(`${SUBDOMAIN_GITLAB}.${DOMAIN}`)
      - traefik.http.routers.gitlab.entrypoints=http,https
      - traefik.http.routers.gitlab.tls.certresolver=letsEncrypt
      - traefik.http.middlewares.gitlab.headers.SSLRedirect=true
      - traefik.http.middlewares.gitlab.headers.STSSeconds=315360000
      - traefik.http.middlewares.gitlab.headers.browserXSSFilter=true
      - traefik.http.middlewares.gitlab.headers.contentTypeNosniff=true
      - traefik.http.middlewares.gitlab.headers.forceSTSHeader=true
      - traefik.http.middlewares.gitlab.headers.SSLHost=${DOMAIN}
      - traefik.http.middlewares.gitlab.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.gitlab.headers.STSPreload=true
      - traefik.http.routers.gitlab.service=gitlab
      
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.http.services.gitlab.loadbalancer.server.scheme=http
      - traefik.http.services.gitlab.loadbalancer.passhostheader=true
networks:
  traefik:
    external: true